// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentToGo.Data;

namespace RentToGo.Migrations
{
    [DbContext(typeof(RentToGoContext))]
    partial class RentToGoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RentToGo.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agent_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Agent_Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Agent_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cust_Id")
                        .HasColumnType("int");

                    b.Property<string>("Office_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Property_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cust_Id");

                    b.HasIndex("Property_Id");

                    b.ToTable("Agent");
                });

            modelBuilder.Entity("RentToGo.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cust_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cust_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cust_FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cust_LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cust_Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cust_Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("RentToGo.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Property_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property_Number_of_Bathrooms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property_Number_of_Bedrooms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property_WeeklyRent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("RentToGo.Models.Agent", b =>
                {
                    b.HasOne("RentToGo.Models.Customer", "Cust_")
                        .WithMany()
                        .HasForeignKey("Cust_Id");

                    b.HasOne("RentToGo.Models.Property", "Property_")
                        .WithMany()
                        .HasForeignKey("Property_Id");

                    b.Navigation("Cust_");

                    b.Navigation("Property_");
                });
#pragma warning restore 612, 618
        }
    }
}
